language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pancutan/docker-react -f Dockerfile.dev .

script:
  - docker run pancutan/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker2" # El nombre del proyecto dentro de ELB
  env: "Docker2-env" # Nombre del environment que habiamos creado en ELB
  # edge: true # Solo si da "missing bucket_name error"
  bucket_name: "elasticbeanstalk-us-west-2-599651702009" # Buscar en la consola s3 en cual bucker esta corriendo
  bucket_path: "docker2" # Usar el explorador de la consola s3, o copiar desde app:
  on:
    branch: master # Rama, interesante para tener varios ambientes
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

