language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pancutan/docker-react -f Dockerfile.dev .

script:
  - docker run pancutan/docker-react npm run test -- --coverage
