version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # ignorar esta ruta en la real
      - .:/app
  tests: # Lo mismo, si ports, para testear
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # ignorar esta ruta en la real
      - .:/app
    # Allows us to send signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    stdin_open: true
    tty: true
    # Override CMD del Dockerfile.dev
    command: ["npm", "run", "test"]
